### ISSUE TITLE
.env 

### ISSUE THREAD

**Issue by mojib2014** [WebDevSimplified/spotify-clone#2]
Hey Kyle, I have been following you on github and youtube thanks for all the good resources.
Just wanted to give you a heads up that you have push your .env file with the spotify repo and it contains all of your spotify secrets.

**Comment by blacbrue** [comment]
i think he deleted the spotify developer application so that client id and secret is not valid anymore

**Comment by mojib2014** [comment]
Thanks @jaydenkoh, probably just wanted to mention it (tought maybe he forgot to put it in .gitignore file).
